checkpoint: saving progress authenticating user cloud account
-- contains bug on iCloud setup
icloudpy.exceptions.ICloudPyFailedLoginException: ('Invalid authentication token.', ICloudPyAPIResponseException('Missing apple_id field'))